import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowLeft,Check,ChevronDown,ChevronUp,Clock,FileSpreadsheet,FolderLock,Play,Square,Trash2,Upload,X} from 'lucide-react';
import type {Examination,HistoricalRecord,HistoryImportSummary,Participant,Session} from '../../types';
import {demoHistory,ultrasoundItems,type HistoryVisit,type UltrasoundItem} from './demoData';
import {clearHistory,findHistoryByEmployeeNo,findHistoryByNationalId,historyStats,importHistory} from '../history/db';
import {displayUltrasoundResult,parseHistoryFile} from '../history/excel';
import {cloudNow,completeExamination,getExamination,getRoomExamination,restoreDraft,saveExaminationDraft,startExamination} from '../examination/service';

const demoPatient:Participant={id:'demo-patient',sessionId:'demo-session',sequence:15,employeeNo:'B30040',name:'王小明（虛構）',gender:'男',slot:'07:30～08:00',groupCode:'A',plannedItems:[],checkinNo:'A15',status:'等候中',checkedInAt:new Date().toISOString(),calledAt:null,note:'',updatedAt:''};
const formatTime=(iso:string)=>new Intl.DateTimeFormat('zh-TW',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date(iso));
const formatElapsed=(seconds:number)=>[Math.floor(seconds/3600),Math.floor(seconds%3600/60),seconds%60].map(value=>String(value).padStart(2,'0')).join(':');
const cloudMessage='無法連線至雲端，檢查紀錄尚未完成同步，請確認網路後重試。';

export function UltrasoundRoom({current,participants,onChanged=async()=>undefined}:{current:Session|null;participants:Participant[];onChanged?:()=>Promise<void>}){
  const[room,setRoom]=useState(()=>localStorage.getItem('itri-ultrasound-room')||'診間 1');const[demo,setDemo]=useState(false);const[hasLocalHistory,setHasLocalHistory]=useState<boolean|null>(null);const[mode,setMode]=useState<'nationalId'|'employeeNo'|'list'>('nationalId');const[query,setQuery]=useState('');const[selected,setSelected]=useState<Participant|null>(null);const[localPerson,setLocalPerson]=useState<{name:string;employeeNo:string}|null>(null);const[records,setRecords]=useState<HistoricalRecord[]>([]);const[items,setItems]=useState<UltrasoundItem[]>([]);const[expanded,setExpanded]=useState<UltrasoundItem[]>([]);const[examination,setExamination]=useState<Examination|null>(null);const[clockOffset,setClockOffset]=useState(0);const[now,setNow]=useState(Date.now());const[confirming,setConfirming]=useState(false);const[actualItems,setActualItems]=useState<UltrasoundItem[]>([]);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[importOpen,setImportOpen]=useState(false);const inputRef=useRef<HTMLInputElement>(null);
  const locked=examination?.status==='in_progress';
  const elapsed=examination?Math.max(0,Math.floor((now+clockOffset-Date.parse(examination.startedAt))/1000)):0;
  useEffect(()=>{void historyStats().then(value=>setHasLocalHistory(value.recordCount>0));},[importOpen]);
  useEffect(()=>{if(!locked)localStorage.setItem('itri-ultrasound-room',room);},[room,locked]);
  useEffect(()=>{if(!examination||examination.status!=='in_progress')return;const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer);},[examination]);
  const applyExamination=useCallback(async(value:Examination,person?:Participant)=>{setExamination(value);setItems(value.selectedItems as UltrasoundItem[]);setSelected(person??participants.find(p=>p.id===value.participantId)??null);if(value.status==='in_progress'){setRoom(value.roomId);try{setClockOffset((await cloudNow()).offsetMs);}catch{setClockOffset(0);}}},[participants]);
  useEffect(()=>{if(demo){setSelected(demoPatient);setItems([]);setExamination(null);setMessage('');return;}setSelected(null);setItems([]);setExamination(null);if(!current)return;void getRoomExamination(current.id,room).then(value=>{if(value)void applyExamination(value);}).catch(()=>setMessage(cloudMessage));},[demo,current?.id,room,participants.length]); // eslint-disable-line react-hooks/exhaustive-deps
  const selectPerson=async(person:Participant|null,history:HistoricalRecord[]=[] )=>{setSelected(person);setRecords(history);setExamination(null);setItems([]);setMessage('');if(!person||demo)return;try{const existing=await getExamination(person.id);if(existing){await applyExamination(existing,person);if(existing.roomId!==room&&existing.status==='in_progress')setMessage(`此受檢者正在${existing.roomId}檢查中。`);return;}const draft=await restoreDraft(person.id);if(draft)setItems(draft.items.filter(item=>ultrasoundItems.includes(item as UltrasoundItem)) as UltrasoundItem[]);}catch{setMessage(cloudMessage);}};
  const search=async(raw=query)=>{if(demo){await selectPerson(demoPatient);return;}const normalized=raw.trim().toUpperCase();const foundRecords=mode==='nationalId'?await findHistoryByNationalId(normalized):mode==='employeeNo'?await findHistoryByEmployeeNo(raw.trim()):[];const newest=[...foundRecords].sort((a,b)=>b.date.localeCompare(a.date))[0];setLocalPerson(newest?{name:newest.name,employeeNo:newest.employeeNo}:null);const employeeNo=mode==='employeeNo'?raw.trim():newest?.employeeNo;const person=participants.find(p=>p.employeeNo===employeeNo)??null;await selectPerson(person,foundRecords);if(!person)setMessage('今日排程查無此受檢者。');};
  const toggle=(item:UltrasoundItem)=>{const next=items.includes(item)?items.filter(x=>x!==item):[...items,item];setItems(next);setExpanded(old=>old.includes(item)?old:[...old,item]);if(selected&&!demo)void saveExaminationDraft(selected.id,room,next);};
  const begin=async()=>{if(!current||!selected){setMessage('今日排程查無此受檢者。');return;}if(!selected.checkedInAt||!selected.checkinNo){setMessage('此受檢者尚未報到，請先至健檢報到站完成報到。');return;}if(!items.length){setMessage('請至少選擇一種超音波項目。');return;}setBusy(true);setMessage('');try{if(demo){const iso=new Date().toISOString();setExamination({id:'demo',participantId:selected.id,roomId:room,startedAt:iso,completedAt:null,durationSeconds:null,selectedItems:items,actualItems:[],itemCount:0,status:'in_progress'});}else{await applyExamination(await startExamination(selected.id,room,items),selected);await onChanged();}}catch(error){const detail=error instanceof Error?error.message:'';setMessage(detail.includes('examination_in_other_room')?`此受檢者正在${detail.split(':').at(-1)}檢查中。`:detail.includes('already_completed')?'此受檢者已完成本次檢查。':cloudMessage);}finally{setBusy(false);}};
  const finish=async()=>{if(!examination||!selected||!actualItems.length)return;setBusy(true);setMessage('');try{if(demo){const iso=new Date().toISOString();setExamination({...examination,status:'completed',completedAt:iso,durationSeconds:Math.max(0,Math.floor((Date.parse(iso)-Date.parse(examination.startedAt))/1000)),actualItems,itemCount:actualItems.length});}else{setExamination(await completeExamination(selected.id,examination.roomId,actualItems));await onChanged();}setConfirming(false);}catch{setMessage(cloudMessage);}finally{setBusy(false);}};
  const history=(item:UltrasoundItem):HistoryVisit[]=>demo?demoHistory[item].slice(0,3):records.filter(record=>record.type===item).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3).map(record=>({date:record.date,result:record.values.整體結果??record.values.結果??'',details:record.values,labs:record.values}));
  const next=()=>{setSelected(null);setLocalPerson(null);setRecords([]);setItems([]);setExpanded([]);setExamination(null);setQuery('');setMessage('');setTimeout(()=>inputRef.current?.focus(),0);};
  if(importOpen)return <ImportDialog close={()=>setImportOpen(false)}/>;
  return <section className="room-workspace"><header className="room-toolbar"><div className="min-w-0"><h2 className="text-xl font-black">超音波診間</h2><p className="truncate font-bold text-teal-100">{current?.companyName??(demo?'XX 公司（虛構展示）':'尚未選擇場次')} ｜ {(current?.sessionDate??new Date().toISOString().slice(0,10)).replaceAll('-','/')}</p></div><label className="flex items-center gap-2"><span className="whitespace-nowrap font-bold">診間</span><select disabled={locked} className="input min-w-28 border-teal-600 text-slate-900 disabled:opacity-60" value={room} onChange={e=>setRoom(e.target.value)}>{[1,2,3,4].map(x=><option key={x}>診間 {x}</option>)}</select></label><div className="ml-auto flex gap-2"><button role="switch" disabled={locked} aria-checked={demo} className={demo?'bg-sky-100 text-sky-900 secondary':'secondary'} onClick={()=>setDemo(x=>!x)}>{demo?'展示模式：開':'展示模式'}</button><button className="secondary" onClick={()=>setImportOpen(true)}><FileSpreadsheet size={19}/>歷年資料管理</button></div></header>
    {message&&<div role="alert" className="room-message">{message}</div>}
    <div className="room-columns"><aside className="room-controls"><div className="room-control-card rounded-xl bg-white shadow-sm"><div className="flex items-center justify-between"><h3 className="text-lg font-black">受檢者</h3>{selected&&!locked&&examination?.status!=='completed'&&<button className="secondary min-h-11 px-3" onClick={next}>換下一位</button>}</div>{!selected&&!locked&&examination?.status!=='completed'&&<><div className="my-3 grid grid-cols-3 gap-2">{([['nationalId','身分證'],['employeeNo','工號'],['list','今日排程']] as const).map(([id,label])=><button key={id} className={mode===id?'primary px-2':'secondary px-2'} onClick={()=>{setMode(id);next();}}>{label}</button>)}</div>{mode==='list'?<select className="input" value="" onChange={async e=>{const person=participants.find(p=>p.id===e.target.value)??null;await selectPerson(person,person?await findHistoryByEmployeeNo(person.employeeNo):[]);}}><option value="">選擇今日受檢者</option>{demo&&<option value={demoPatient.id}>A15 王小明（虛構）</option>}{participants.map(p=><option value={p.id} key={p.id}>{p.checkinNo??'未報到'} {p.name}（{p.employeeNo}）</option>)}</select>:<div className="flex gap-2"><input ref={inputRef} className="input min-w-0 flex-1" autoComplete="off" value={query} placeholder={mode==='nationalId'?'請掃描或輸入身分證':'請輸入工號'} onChange={e=>{setQuery(e.target.value);if(demo||(mode==='nationalId'&&e.target.value.trim().length>=10))void search(e.target.value);}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void search(e.currentTarget.value);}}}/><button className="primary px-4" onClick={()=>void search()}>查詢</button></div>}</>}{selected?<CompactPatient patient={selected} examination={examination} room={room}/>:localPerson?<p className="mt-3 rounded-lg bg-amber-50 p-3 font-bold">{localPerson.name}（{localPerson.employeeNo}）今日排程查無此人。</p>:<p className="mt-3 text-slate-500">尚未選取受檢者。</p>}</div>
      <div className="room-control-card rounded-xl bg-white shadow-sm"><h3 className="text-lg font-black">本次檢查</h3><div className="room-exam-list mt-3">{ultrasoundItems.map(item=>{const on=items.includes(item);return <button aria-pressed={on} key={item} disabled={!selected||Boolean(examination)} onClick={()=>toggle(item)} className={`room-exam-button flex w-full items-center gap-3 rounded-xl border-2 px-3 text-left text-base font-black transition disabled:opacity-60 ${on?'border-teal-700 bg-teal-700 text-white shadow-md':'border-slate-200 bg-white text-slate-800'}`}><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full border-2 border-current">{on&&<Check size={19}/>}</span>{item}</button>})}</div><p className="mt-3 rounded-lg bg-slate-100 p-2 text-center font-black">本次已選擇：<span className="text-teal-700">{items.length}</span> 項</p></div></aside>
      <main className="room-history"><h3 className="mb-3 text-xl font-black">歷年超音波資料</h3>{!demo&&hasLocalHistory===false?<div className="rounded-2xl bg-white p-8 text-center font-bold text-slate-600">本台裝置尚未匯入歷年超音波資料。</div>:!items.length?<div className="rounded-2xl bg-white p-8 text-center text-slate-500">選取本次超音波項目後，將在此顯示各項最近三次紀錄。</div>:<div className="space-y-4">{items.map(item=><HistoryPanel key={item} item={item} visits={history(item)} open={expanded.includes(item)} toggle={()=>setExpanded(old=>old.includes(item)?old.filter(x=>x!==item):[...old,item])}/>)}</div>}</main></div>
    <footer className="room-actions">{!examination&&<button disabled={busy||!selected||!items.length} className="primary min-h-14 w-full text-lg disabled:opacity-40" onClick={()=>void begin()}><Play/>{busy?'雲端確認中…':'開始檢查'}</button>}{examination?.status==='in_progress'&&<><div role="status" className="flex flex-wrap items-center gap-x-4 rounded-xl bg-amber-50 px-4 py-2 text-amber-950"><b className="text-lg">檢查中</b><span>開始 {formatTime(examination.startedAt)}</span><span className="text-xl font-black tabular-nums">{formatElapsed(elapsed)}</span></div><button disabled={busy} className="secondary min-h-14 min-w-52 border-teal-700 text-lg text-teal-800" onClick={()=>{setActualItems([...items]);setConfirming(true);}}><Square/>完成檢查</button></>}{examination?.status==='completed'&&<div role="status" className="flex w-full flex-wrap items-center justify-between gap-3 rounded-xl bg-emerald-50 px-4 py-2 text-emerald-950"><p><b className="text-xl">檢查已完成</b> 總耗時 {formatElapsed(examination.durationSeconds??0)} 完成 {examination.itemCount} 件</p><button className="primary" onClick={next}>下一位受檢者</button></div>}</footer>
    {confirming&&<div className="fixed inset-0 z-50 grid bg-slate-950/60 p-3" role="dialog" aria-modal="true"><div className="m-auto w-full max-w-lg rounded-2xl bg-white p-6"><div className="flex justify-between"><h3 className="text-xl font-black">確認本次實際完成的超音波項目</h3><button className="secondary px-3" onClick={()=>setConfirming(false)}><X/></button></div><div className="my-5 space-y-2">{items.map(item=><label key={item} className="flex min-h-14 items-center gap-3 rounded-xl border p-3 text-lg font-bold"><input type="checkbox" className="h-6 w-6" checked={actualItems.includes(item)} onChange={()=>setActualItems(old=>old.includes(item)?old.filter(x=>x!==item):[...old,item])}/>{item}</label>)}</div><p className="mb-3 text-sm">實際完成項目至少要有一項。</p><button disabled={busy||!actualItems.length} className="primary w-full disabled:opacity-40" onClick={()=>void finish()}>{busy?'同步中…':'確認完成並同步雲端'}</button></div></div>}
    </section>;
}
function CompactPatient({patient,examination,room}:{patient:Participant;examination:Examination|null;room:string}){return <div className="mt-3 border-l-4 border-teal-700 pl-3"><div className="flex items-baseline gap-3"><b className="text-2xl text-teal-800">{patient.checkinNo??'—'}</b><strong className="text-2xl">{patient.name}</strong></div><dl className="mt-2 grid grid-cols-[4rem_1fr] gap-y-1"><dt className="text-slate-500">工號</dt><dd className="font-bold">{patient.employeeNo}</dd><dt className="text-slate-500">時段</dt><dd className="font-bold">{patient.slot}</dd><dt className="text-slate-500">狀態</dt><dd className="font-bold">{examination?.status==='in_progress'?`檢查中・${examination.roomId}`:examination?.status==='completed'?'已完成':`${patient.status}・${room}`}</dd></dl></div>}
function InfoBlock({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div><p className="text-sm font-bold text-slate-500">{label}</p><p className={`mt-1 font-black ${strong?'text-3xl text-teal-800':'text-xl'}`}>{value}</p></div>}
function HistoryPanel({item,visits,open,toggle}:{item:UltrasoundItem;visits:HistoryVisit[];open:boolean;toggle:()=>void}){return <article className="overflow-hidden rounded-2xl bg-white shadow-sm"><button aria-expanded={open} onClick={toggle} className="flex min-h-14 w-full items-center justify-between px-5 py-3 text-left text-xl font-black"><span>{item}｜最近三次</span>{open?<ChevronUp/>:<ChevronDown/>}</button>{open&&<div className="border-t p-3 sm:p-4">{!visits.length?<p className="rounded-xl bg-slate-50 p-8 text-center font-bold text-slate-600">查無此項目歷年檢查紀錄。</p>:item==='腹部超音波'?<AbdominalTable visits={visits}/>:<div className="grid gap-3 lg:grid-cols-3">{visits.map(visit=><div key={visit.date} className="rounded-xl border p-4"><p className="flex items-center gap-2 text-lg font-black text-teal-800"><Clock size={19}/>{visit.date}</p>{Object.entries(visit.details??{結果:visit.result}).map(([label,value])=><p key={label} className="mt-2 whitespace-pre-wrap text-lg leading-7"><b>{label}：</b>{displayUltrasoundResult(value)}</p>)}</div>)}</div>}<p className="mt-2 text-sm font-medium text-slate-600">原始結果僅供診間核對，系統不進行摘要或醫療判讀。</p></div>}</article>}
function AbdominalTable({visits}:{visits:HistoryVisit[]}){const rows=[['整體結果','整體結果'],['肝臟','肝臟'],['膽囊','膽囊'],['胰臟','胰臟'],['脾臟','脾臟'],['腎臟','腎臟'],['其他','其他']];return <div className="abdominal-history"><div className="overflow-x-auto"><table><thead><tr><th>部位</th>{visits.map(v=><th key={v.date}>{v.date}</th>)}</tr></thead><tbody>{rows.map(([label,key])=><tr key={key}><th>{label}</th>{visits.map(v=><td key={v.date}>{displayUltrasoundResult(v.details?.[key]??'')}</td>)}</tr>)}</tbody></table></div><h4>B、C 肝原始檢驗資料</h4><div className="overflow-x-auto"><table><thead><tr><th>項目</th>{visits.map(v=><th key={v.date}>{v.date}</th>)}</tr></thead><tbody>{['HBsAg','Anti-HBs','Anti-HCV'].map(lab=><tr key={lab}><th>{lab}</th>{visits.map(v=><td key={v.date}>{v.labs?.[lab]??''}</td>)}</tr>)}</tbody></table></div></div>}
type ImportProgress={fileName:string;fileIndex:number;fileCount:number;stage:string;processed:number;total:number;percent:number};
type FileImportReport={fileName:string;sourceRows:number;validRecords:number;summary:HistoryImportSummary;errors:string[]};
const emptySummary=():HistoryImportSummary=>({inserted:0,skipped:0,pending:0,failed:0});
function ImportDialog({close}:{close:()=>void}){
  const[stats,setStats]=useState<Awaited<ReturnType<typeof historyStats>>|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[summary,setSummary]=useState<HistoryImportSummary>(emptySummary());const[progress,setProgress]=useState<ImportProgress|null>(null);const[reports,setReports]=useState<FileImportReport[]>([]);
  const reload=()=>historyStats().then(setStats);useEffect(()=>{void reload();},[]);
  const choose=async(files:File[])=>{
    setBusy(true);setMessage('');setReports([]);const total=emptySummary();const completed:FileImportReport[]=[];
    try{
      for(let fileIndex=0;fileIndex<files.length;fileIndex++){
        const file=files[fileIndex];const update=(stage:string,processed=0,rowTotal=0)=>setProgress({fileName:file.name,fileIndex:fileIndex+1,fileCount:files.length,stage,processed,total:rowTotal,percent:rowTotal?Math.round(processed/rowTotal*100):0});
        try{
          update('正在讀取 Excel……');
          const parsed=await parseHistoryFile(file,event=>update(event.stage==='reading'?'正在讀取 Excel……':event.stage==='headers'?'正在辨識表頭……':`正在解析第 ${event.processed.toLocaleString()} / ${event.total.toLocaleString()} 列……`,event.processed,event.total));
          if(parsed.missing.length){
            const reason=`無法匯入：${file.name}\n工作表：${parsed.sheetName}\n原因：無法辨識必要表頭。\n已辨識表頭：${parsed.headers.join('、')||'（無）'}\n缺少欄位：${parsed.missing.join('、')}\n請確認 Excel 表頭是否在第一列，或選擇正確工作表。`;
            total.failed+=parsed.sourceRows||1;completed.push({fileName:file.name,sourceRows:parsed.sourceRows,validRecords:0,summary:{...emptySummary(),failed:parsed.sourceRows||1},errors:[reason]});setReports([...completed]);continue;
          }
          update('正在比對既有資料……',0,parsed.records.length);
          const result=await importHistory(parsed.records,file.name,{sourceRows:parsed.sourceRows,onProgress:value=>update(`正在寫入第 ${value.batch} / ${value.batches} 批……`,value.processed,value.total)});
          result.failed+=parsed.failed;for(const key of Object.keys(total) as (keyof HistoryImportSummary)[])total[key]+=result[key];
          completed.push({fileName:file.name,sourceRows:parsed.sourceRows,validRecords:parsed.records.length,summary:result,errors:parsed.rowErrors.slice(0,100).map(item=>`第 ${item.row} 列：${item.reason}`)});setReports([...completed]);setSummary({...total});
        }catch(error){total.failed++;completed.push({fileName:file.name,sourceRows:0,validRecords:0,summary:{...emptySummary(),failed:1},errors:[error instanceof Error?error.message:'無法解析 Excel。']});setReports([...completed]);setSummary({...total});}
      }
      setMessage(completed.some(report=>report.summary.failed||report.errors.length)?'匯入已結束，部分資料未成功；請查看下方摘要。':'匯入完成。');
    }finally{setBusy(false);setProgress(old=>old?{...old,stage:'匯入完成。',percent:100}:old);await reload();}
  };
  return <section className="mx-auto max-w-4xl"><header className="mb-5 flex items-center gap-4 border-b border-slate-200 pb-4"><button className="secondary" onClick={close}><ArrowLeft size={19}/>返回超音波診間</button><div><h2 className="text-2xl font-black">歷年資料管理</h2><p className="text-sm text-slate-600">支援一次選取多份正式健檢結果 Excel。</p></div></header><div className="rounded-2xl bg-white p-6 shadow-sm"><div className="mb-4 rounded-xl border-2 border-emerald-300 bg-emerald-50 p-4"><p className="flex gap-2 font-black text-emerald-950"><FolderLock/>歷年醫療資料只保存在本台裝置</p><p className="mt-2 text-sm text-emerald-900">身分證與歷年結果不會上傳 Supabase。</p></div>
    <div className="grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-4"><InfoBlock label="匯入檔案" value={`${stats?.fileCount??0} 份`}/><InfoBlock label="有效紀錄" value={`${stats?.recordCount??0} 筆`}/><InfoBlock label="涵蓋年份" value={stats?.years.join('、')||'—'}/><InfoBlock label="最近匯入" value={stats?.lastImportAt?new Date(stats.lastImportAt).toLocaleString('zh-TW'):'—'}/></div>
    <div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><InfoBlock label="本次新增" value={String(summary.inserted)}/><InfoBlock label="重複略過" value={String(summary.skipped)}/><InfoBlock label="待確認" value={String(summary.pending)}/><InfoBlock label="失敗" value={String(summary.failed)}/></div>
    <label className="secondary mt-5 w-full cursor-pointer border-dashed border-teal-600"><Upload/>{busy?'匯入處理中…':'選擇多份 Excel'}<input disabled={busy} type="file" accept=".xlsx,.xls" multiple className="sr-only" onChange={e=>{const selected=Array.from(e.target.files??[]);e.target.value='';void choose(selected);}}/></label>
    {progress&&<div className="mt-3 rounded-xl bg-sky-50 p-4" role="status"><b>{progress.fileName}（第 {progress.fileIndex} / {progress.fileCount} 份）</b><p>{progress.stage}</p><p>{progress.processed.toLocaleString()} / {progress.total.toLocaleString()} 筆（{progress.percent}%）</p><div className="mt-2 h-2 overflow-hidden rounded bg-sky-200"><div className="h-full bg-sky-700" style={{width:`${progress.percent}%`}}/></div></div>}
    {message&&<p className="mt-3 whitespace-pre-wrap rounded-xl bg-slate-100 p-3" role="alert">{message}</p>}
    {reports.map(report=><section key={report.fileName} className="mt-3 rounded-xl border p-4"><h4 className="font-black">{report.fileName}</h4><p className="mt-1 text-sm">來源資料列數：{report.sourceRows}；有效超音波紀錄數：{report.validRecords}；新增成功：{report.summary.inserted}；完全重複略過：{report.summary.skipped}；待人工確認：{report.summary.pending}；失敗：{report.summary.failed}</p>{report.errors.length>0&&<details className="mt-2"><summary className="cursor-pointer font-bold">錯誤摘要（{report.errors.length}）</summary><ul className="mt-2 list-disc space-y-1 pl-5 text-sm">{report.errors.map((error,index)=><li className="whitespace-pre-wrap" key={index}>{error}</li>)}</ul></details>}</section>)}
    <button disabled={busy||!stats?.recordCount} className="secondary mt-5 w-full border-red-300 text-red-800 disabled:opacity-40" onClick={async()=>{if(confirm('確定清除本台裝置全部歷年超音波資料？此操作無法復原。')){await clearHistory();setSummary(emptySummary());setReports([]);setMessage('本機歷年資料已清除。');await reload();}}}><Trash2/>清除本機歷年資料</button>{stats&&!stats.recordCount&&<p className="mt-3 text-center font-bold text-slate-600">本台裝置尚未匯入歷年超音波資料。</p>}{stats&&stats.pending>0&&<p className="mt-3 rounded-xl bg-amber-50 p-3 font-bold text-amber-900">目前有 {stats.pending} 筆同人、同日、同項目但內容不同的待確認資料，未自動覆蓋。</p>}</div></section>;
}
