import {useEffect,useMemo,useRef,useState} from 'react';
import {Check,ChevronDown,ChevronUp,Clock,FileSpreadsheet,FolderLock,Play,Square,Upload} from 'lucide-react';
import type {Participant,Session} from '../../types';
import {demoHistory,ultrasoundItems,type HistoryVisit,type UltrasoundItem} from './demoData';

const demoPatient:Participant={id:'demo-patient',sessionId:'demo-session',sequence:15,employeeNo:'B30040',name:'王小明（虛構）',gender:'男',slot:'07:30～08:00',groupCode:'A',plannedItems:[],checkinNo:'A15',status:'等候中',checkedInAt:null,calledAt:null,note:'',updatedAt:''};
const formatTime=(date:Date)=>date.toLocaleTimeString('zh-TW',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false});

export function UltrasoundRoom({current,participants}:{current:Session|null;participants:Participant[]}){
  const[room,setRoom]=useState('診間 1');const[demo,setDemo]=useState(true);const[mode,setMode]=useState<'nationalId'|'employeeNo'|'list'>('nationalId');const[query,setQuery]=useState('');const[selected,setSelected]=useState<Participant|null>(demoPatient);const[items,setItems]=useState<UltrasoundItem[]>(['腹部超音波','乳房超音波']);const[expanded,setExpanded]=useState<UltrasoundItem[]>(['腹部超音波','乳房超音波']);const[startedAt,setStartedAt]=useState<string|null>(null);const[finished,setFinished]=useState<{time:string;items:UltrasoundItem[]}|null>(null);const[importOpen,setImportOpen]=useState(false);const[files,setFiles]=useState<File[]>([]);const inputRef=useRef<HTMLInputElement>(null);
  const available=useMemo(()=>participants.filter(p=>p.checkedInAt||p.status!=='未報到'),[participants]);
  useEffect(()=>{if(demo){setSelected(demoPatient);setQuery('');}else{setSelected(null);setItems([]);setExpanded([]);setStartedAt(null);setFinished(null);}},[demo]);
  const search=()=>{if(demo){setSelected(demoPatient);return;}const normalized=query.trim().toUpperCase();const found=mode==='employeeNo'?available.find(p=>p.employeeNo.toUpperCase()===normalized):null;setSelected(found??null);};
  const toggle=(item:UltrasoundItem)=>{setItems(old=>old.includes(item)?old.filter(x=>x!==item):[...old,item]);setExpanded(old=>old.includes(item)?old:[...old,item]);setFinished(null);};
  const history=(item:UltrasoundItem):HistoryVisit[]=>demo?demoHistory[item].slice(0,3):[];
  return <section className="space-y-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h2 className="text-2xl font-black">超音波診間</h2><p className="mt-1 text-slate-500">平板操作介面第一版・開始與完成操作目前僅供預覽。</p></div><button className="secondary" onClick={()=>setImportOpen(true)}><FileSpreadsheet size={20}/>匯入／管理歷年超音波資料</button></div>
    <div className="grid gap-4 rounded-2xl bg-teal-800 p-5 text-white shadow-sm md:grid-cols-[1fr_1fr_220px]"><Info label="目前公司" value={current?.companyName??(demo?'XX 公司（虛構展示）':'尚未選擇場次')}/><Info label="健檢日期" value={(current?.sessionDate??'2026-09-24').replaceAll('-','/')}/><label><span className="mb-1 block text-sm font-bold text-teal-100">診間名稱</span><select className="input border-teal-600 text-slate-900" value={room} onChange={e=>setRoom(e.target.value)}>{[1,2,3,4].map(x=><option key={x}>診間 {x}</option>)}</select></label></div>
    <div className="rounded-2xl border-2 border-sky-200 bg-sky-50 p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><b className="text-sky-950">虛構資料 UI 展示模式</b><p className="text-sm text-sky-800">展示資料不會讀取、修改或寫入 Supabase。</p></div><button role="switch" aria-checked={demo} className={demo?'primary':'secondary'} onClick={()=>setDemo(x=>!x)}>{demo?'展示模式：開啟':'正式資料模式'}</button></div></div>
    <div className="rounded-2xl bg-white p-5 shadow-sm"><h3 className="text-lg font-black">受檢者查詢</h3><div className="my-4 grid gap-2 sm:grid-cols-3">{([['nationalId','身分證'],['employeeNo','工號'],['list','已報到清單']] as const).map(([id,label])=><button key={id} className={mode===id?'primary':'secondary'} onClick={()=>{setMode(id);setSelected(demo?demoPatient:null);setQuery('');setTimeout(()=>inputRef.current?.focus(),0);}}>{label}</button>)}</div>{mode==='list'?<select className="input" value={selected?.id??''} onChange={e=>setSelected(available.find(p=>p.id===e.target.value)??null)}><option value="">選擇已報到受檢者</option>{demo&&<option value={demoPatient.id}>A15 王小明（虛構）</option>}{available.map(p=><option value={p.id} key={p.id}>{p.checkinNo??'—'} {p.name}（{p.employeeNo}）</option>)}</select>:<div className="flex flex-col gap-2 sm:flex-row"><input ref={inputRef} className="input flex-1" autoComplete="off" value={query} placeholder={mode==='nationalId'?'請掃描或輸入身分證':'請輸入工號'} onChange={e=>{setQuery(e.target.value);if(demo||e.target.value.trim().length>=10)search();}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();search();}}}/><button className="primary sm:w-32" onClick={search}>查詢</button></div>} {!demo&&mode==='nationalId'&&<p className="mt-2 text-sm text-slate-500">身分證查詢須待本機歷年資料串接；身分證不會上傳 Supabase。</p>}</div>
    {selected?<PatientCard patient={selected}/>:<div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center text-slate-500">尚未選取受檢者。請查詢工號或從已報到清單選擇；本機身分證對照將於後續版本串接。</div>}
    <div className="rounded-2xl bg-white p-5 shadow-sm"><h3 className="text-xl font-black">本次超音波檢查項目</h3><p className="mt-1 text-sm text-slate-500">由診間人員手動選擇，可同時選取多項；不依健檢方案自動判定。</p><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{ultrasoundItems.map(item=>{const on=items.includes(item);return <button aria-pressed={on} key={item} disabled={!selected||!!startedAt} onClick={()=>toggle(item)} className={`touch-card flex flex-col items-center justify-center gap-2 rounded-2xl border-2 p-4 text-lg font-black transition disabled:opacity-40 ${on?'border-teal-700 bg-teal-700 text-white shadow-lg':'border-slate-200 bg-white text-slate-800 active:bg-slate-100'}`}>{on?<Check size={30}/>:<span className="h-[30px]"/>}{item}</button>})}</div><p className="mt-4 rounded-xl bg-slate-100 p-3 text-center text-lg font-black">本次已選擇：<span className="text-teal-700">{items.length}</span> 項</p></div>
    <div><h3 className="mb-3 text-xl font-black">歷年超音波資料</h3>{!items.length?<div className="rounded-2xl bg-white p-8 text-center text-slate-500">選取本次超音波項目後，將在此顯示各項最近三次紀錄。</div>:<div className="space-y-4">{items.map(item=><HistoryPanel key={item} item={item} visits={history(item)} open={expanded.includes(item)} toggle={()=>setExpanded(old=>old.includes(item)?old.filter(x=>x!==item):[...old,item])}/>)}</div>}</div>
    <div className="sticky bottom-3 rounded-2xl border bg-white p-4 shadow-xl"><div className="grid gap-3 sm:grid-cols-2"><button disabled={!selected||!items.length||!!startedAt} className="primary min-h-16 text-lg disabled:opacity-40" onClick={()=>{setStartedAt(formatTime(new Date()));setFinished(null);}}><Play/>開始檢查</button><button disabled={!startedAt} className="secondary min-h-16 border-teal-700 text-lg text-teal-800 disabled:opacity-40" onClick={()=>{setFinished({time:formatTime(new Date()),items:[...items]});setStartedAt(null);}}><Square/>完成檢查</button></div>{startedAt&&<div role="status" className="mt-3 rounded-xl bg-amber-50 p-4 text-amber-950"><b>檢查中</b>・開始時間 {startedAt}<br/><span className="text-sm">本次選取：{items.join('、')}</span></div>}{finished&&<div role="status" className="mt-3 rounded-xl bg-emerald-50 p-4 text-emerald-950"><b>預覽完成</b>・完成時間 {finished.time}<br/><span className="text-sm">完成 {finished.items.length} 項：{finished.items.join('、')}（未寫入正式資料庫）</span></div>}<p className="mt-2 text-center text-xs text-slate-500">預覽功能：正式檢查開始／完成 RPC 尚未串接，不會寫入 Supabase。</p></div>
    {importOpen&&<ImportDialog files={files} setFiles={setFiles} close={()=>setImportOpen(false)}/>} </section>;
}
function Info({label,value}:{label:string;value:string}){return <div><p className="text-sm font-bold text-teal-100">{label}</p><p className="mt-1 text-xl font-black">{value}</p></div>}
function PatientCard({patient}:{patient:Participant}){return <div className="rounded-2xl border-l-8 border-teal-700 bg-white p-5 shadow-sm"><p className="text-sm font-bold text-teal-700">受檢者基本資料</p><div className="mt-2 grid gap-4 sm:grid-cols-[1.3fr_repeat(3,1fr)]"><div><p className="text-3xl font-black">{patient.name}</p><p className="mt-1 text-slate-500">工號：{patient.employeeNo}</p></div><InfoBlock label="報到編號" value={patient.checkinNo??'—'} strong/><InfoBlock label="排程時段" value={patient.slot}/><InfoBlock label="目前狀態" value={patient.status}/></div></div>}
function InfoBlock({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div><p className="text-sm font-bold text-slate-500">{label}</p><p className={`mt-1 font-black ${strong?'text-3xl text-teal-800':'text-xl'}`}>{value}</p></div>}
function HistoryPanel({item,visits,open,toggle}:{item:UltrasoundItem;visits:HistoryVisit[];open:boolean;toggle:()=>void}){return <article className="overflow-hidden rounded-2xl bg-white shadow-sm"><button aria-expanded={open} onClick={toggle} className="flex min-h-16 w-full items-center justify-between p-5 text-left text-lg font-black"><span>{item}｜最近三次</span>{open?<ChevronUp/>:<ChevronDown/>}</button>{open&&<div className="border-t p-4 sm:p-5">{!visits.length?<p className="rounded-xl bg-slate-50 p-8 text-center font-bold text-slate-500">查無此項目歷年檢查紀錄</p>:item==='腹部超音波'?<AbdominalTable visits={visits}/>:<div className="grid gap-3 lg:grid-cols-3">{visits.map(visit=><div key={visit.date} className="rounded-xl border p-4"><p className="flex items-center gap-2 font-black text-teal-800"><Clock size={17}/>{visit.date}</p><p className="mt-3 whitespace-pre-wrap leading-7">{visit.result}</p></div>)}</div>}<p className="mt-3 text-xs text-slate-500">原始結果僅供診間核對，系統不進行摘要或醫療判讀。</p></div>}</article>}
function AbdominalTable({visits}:{visits:HistoryVisit[]}){const rows=['腹部超音波整體結果','肝臟','膽囊','胰臟','脾臟','腎臟','其他'];return <><div className="overflow-x-auto"><table><thead><tr><th>部位</th>{visits.map(v=><th key={v.date}>{v.date}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row}><th>{row}</th>{visits.map(v=><td className="min-w-48 whitespace-normal align-top" key={v.date}>{row==='腹部超音波整體結果'?v.result:v.details?.[row]??'—'}</td>)}</tr>)}</tbody></table></div><h4 className="mb-2 mt-5 font-black">B、C 肝原始檢驗資料</h4><div className="overflow-x-auto"><table><thead><tr><th>項目</th>{visits.map(v=><th key={v.date}>{v.date}</th>)}</tr></thead><tbody>{['HBsAg','Anti-HBs','Anti-HCV'].map(lab=><tr key={lab}><th>{lab}</th>{visits.map(v=><td key={v.date}>{v.labs?.[lab]??'—'}</td>)}</tr>)}</tbody></table></div></>}
function ImportDialog({files,setFiles,close}:{files:File[];setFiles:(files:File[])=>void;close:()=>void}){return <div className="fixed inset-0 z-50 grid bg-slate-950/60 p-3" role="dialog" aria-modal="true" aria-label="匯入歷年超音波資料"><div className="m-auto max-h-full w-full max-w-2xl overflow-auto rounded-2xl bg-white p-6"><div className="flex items-start justify-between gap-3"><div><h3 className="text-xl font-black">匯入／管理歷年超音波資料</h3><p className="mt-1 text-slate-500">第一版提供檔案選擇與介面預覽。</p></div><button className="secondary px-4" onClick={close}>關閉</button></div><div className="my-5 rounded-xl border-2 border-emerald-300 bg-emerald-50 p-4"><p className="flex gap-2 font-black text-emerald-950"><FolderLock/>歷年醫療資料只保存在本台裝置</p><p className="mt-2 text-sm text-emerald-900">不會上傳 Supabase。請使用受管理的診間平板，並依院所規範保管檔案。</p></div><div className="rounded-xl bg-slate-50 p-4"><b>本台平板資料狀態</b><p className="mt-2 text-slate-600">尚未匯入正式歷年資料・資料庫功能待後續版本串接</p></div><label className="secondary mt-5 w-full cursor-pointer border-dashed border-teal-600"><Upload/>選擇多份 Excel<input type="file" accept=".xlsx,.xls" multiple className="sr-only" onChange={e=>setFiles(Array.from(e.target.files??[]))}/></label>{files.length>0&&<div className="mt-4"><b>已選擇 {files.length} 份檔案（尚未匯入）</b><ul className="mt-2 list-inside list-disc text-sm text-slate-600">{files.map((f,i)=><li key={`${f.name}-${i}`}>{f.name}</li>)}</ul></div>}<p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm leading-6 text-amber-950">Excel 解析、欄位比對、同年多次紀錄與重複資料去重尚未實作。選擇檔案不代表匯入成功。</p></div></div>}
