import {requireSupabase} from '../../lib/supabase';
import type {Examination,UltrasoundItemName} from '../../types';
import {db} from '../history/db';

type ExaminationRow={id:string;participant_id:string;room_id:string;started_at:string;completed_at:string|null;duration_seconds:number|null;selected_items?:string[];actual_items:string[];item_count:number;status:Examination['status']};
const mapExamination=(row:ExaminationRow):Examination=>({id:row.id,participantId:row.participant_id,roomId:row.room_id,startedAt:row.started_at,completedAt:row.completed_at,durationSeconds:row.duration_seconds,selectedItems:(row.selected_items??[]) as UltrasoundItemName[],actualItems:row.actual_items as UltrasoundItemName[],itemCount:row.item_count,status:row.status});

export async function getExamination(participantId:string){const{data,error}=await requireSupabase().from('examinations').select('*').eq('participant_id',participantId).maybeSingle();if(error)throw error;return data?mapExamination(data as ExaminationRow):null;}
export async function getRoomExamination(sessionId:string,roomId:string){const{data,error}=await requireSupabase().from('examinations').select('*,participants!inner(session_id)').eq('participants.session_id',sessionId).eq('room_id',roomId).eq('status','in_progress').maybeSingle();if(error)throw error;return data?mapExamination(data as unknown as ExaminationRow):null;}
export async function listExaminations(participantIds:string[]){if(!participantIds.length)return[];const{data,error}=await requireSupabase().from('examinations').select('*').in('participant_id',participantIds);if(error)throw error;return(data as ExaminationRow[]).map(mapExamination);}
export async function cloudNow(){const before=Date.now();const{data,error}=await requireSupabase().rpc('examination_clock');const after=Date.now();if(error)throw error;const server=Date.parse(data as string);return{iso:new Date(server).toISOString(),offsetMs:server-Math.round((before+after)/2)};}
export async function saveExaminationDraft(participantId:string,roomId:string,items:UltrasoundItemName[],startedAt:string|null=null){await db.drafts.put({participantId,roomId,items,startedAt});}
export async function startExamination(participantId:string,roomId:string,items:UltrasoundItemName[]){await saveExaminationDraft(participantId,roomId,items);const{data,error}=await requireSupabase().rpc('start_examination',{p_participant_id:participantId,p_room_id:roomId,p_selected_items:items});if(error)throw error;const examination=mapExamination(data as ExaminationRow);await saveExaminationDraft(participantId,examination.roomId,examination.selectedItems,examination.startedAt);return examination;}
export async function completeExamination(participantId:string,roomId:string,items:UltrasoundItemName[]){const{data,error}=await requireSupabase().rpc('complete_examination',{p_participant_id:participantId,p_room_id:roomId,p_actual_items:items});if(error)throw error;const examination=mapExamination(data as ExaminationRow);await db.drafts.delete(participantId);return examination;}
export async function restoreDraft(participantId:string){return db.drafts.get(participantId);}
