import type {DailySchedulePerson,MasterPerson,MatchResult,PreparedPerson,RosterIssueCode} from './types';

export const issueLabels:Record<RosterIssueCode,string>={master_not_found:'工號在大名單找不到',name_mismatch:'工號相同但姓名不同',activity_mismatch:'活動項目不一致',duplicate_master:'大名單有重複工號',duplicate_daily:'每日排程有重複工號',missing_master_data:'大名單缺少必要資料',incomplete_daily:'每日排程資料不完整'};
const newId=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`;
export function matchRoster(master:MasterPerson[],daily:DailySchedulePerson[]):MatchResult{
  const byEmployee=new Map<string,MasterPerson[]>();for(const person of master)byEmployee.set(person.employeeNo,[...(byEmployee.get(person.employeeNo)??[]),person]);
  const dailyCounts=new Map<string,number>();for(const person of daily)dailyCounts.set(person.employeeNo,(dailyCounts.get(person.employeeNo)??0)+1);
  const all=daily.map((day,index):PreparedPerson=>{const candidates=byEmployee.get(day.employeeNo)??[];const person=candidates[0];const issues:RosterIssueCode[]=[];if(!day.employeeNo||!day.name||!day.scheduleDate||!day.slot||!day.activity)issues.push('incomplete_daily');if(!person)issues.push('master_not_found');if(candidates.length>1)issues.push('duplicate_master');if((dailyCounts.get(day.employeeNo)??0)>1)issues.push('duplicate_daily');if(person&&person.name!==day.name)issues.push('name_mismatch');if(person&&person.originalActivity!==day.activity)issues.push('activity_mismatch');if(person&&(!person.nationalId||!person.gender||!person.item))issues.push('missing_master_data');return{localId:newId(),sequence:index+1,employeeNo:day.employeeNo,name:day.name,gender:person?.gender??'',scheduleDate:day.scheduleDate,slot:day.slot,item:person?.item??'',extension:day.extension||person?.extension||'',nationalId:person?.nationalId??'',originalActivity:person?.originalActivity??'',dailyActivity:day.activity,issues,confirmed:false};});
  return{ready:all.filter(row=>!row.issues.length),pending:all.filter(row=>row.issues.length)};
}
export function makePreparedFromMaster(person:MasterPerson,date:string,slot:string,sequence:number):PreparedPerson{return{localId:newId(),sequence,employeeNo:person.employeeNo,name:person.name,gender:person.gender,scheduleDate:date,slot,item:person.item,extension:person.extension,nationalId:person.nationalId,originalActivity:person.originalActivity,dailyActivity:person.originalActivity,issues:[],confirmed:true};}
