import {requireSupabase} from '../../lib/supabase'; import type {ImportResult,Participant} from '../../types'; import type {ScheduleRow} from './excel';
import type {PreparedPerson} from '../roster/types';
import {groupForSlot} from './rules';
type ParticipantRow={id:string;session_id:string;sequence_no:number;employee_no:string;full_name:string;gender:string;schedule_slot:string;group_code:Participant['groupCode'];planned_items:string[];checkin_no:string|null;status:Participant['status'];checked_in_at:string|null;called_at:string|null;note:string;updated_at:string};
export const mapParticipant=(r:ParticipantRow):Participant=>({id:r.id,sessionId:r.session_id,sequence:r.sequence_no,employeeNo:r.employee_no,name:r.full_name,gender:r.gender,slot:r.schedule_slot,groupCode:r.group_code,plannedItems:r.planned_items,checkinNo:r.checkin_no,status:r.status,checkedInAt:r.checked_in_at,calledAt:r.called_at,note:r.note,updatedAt:r.updated_at});
export async function listParticipants(sessionId:string){const{data,error}=await requireSupabase().from('participants').select('*').eq('session_id',sessionId).order('sequence_no');if(error)throw error;return(data as ParticipantRow[]).map(mapParticipant);}
export async function findParticipant(sessionId:string,employeeNo:string){const{data,error}=await requireSupabase().from('participants').select('*').eq('session_id',sessionId).eq('employee_no',employeeNo).maybeSingle();if(error)throw error;return data?mapParticipant(data as ParticipantRow):null;}
export async function importSchedule(sessionId:string,rows:ScheduleRow[]):Promise<ImportResult>{const existing=await listParticipants(sessionId);const keys=new Set(existing.map(p=>p.employeeNo));const unique:ScheduleRow[]=[];const batch=new Set<string>();for(const row of rows){if(keys.has(row.employeeNo)||batch.has(row.employeeNo))continue;batch.add(row.employeeNo);unique.push(row);}if(unique.length){const payload=unique.map(r=>({session_id:sessionId,sequence_no:r.sequence,employee_no:r.employeeNo,full_name:r.name,gender:r.gender,schedule_slot:r.slot,group_code:r.groupCode,planned_items:r.items}));const{error}=await requireSupabase().from('participants').insert(payload);if(error)throw error;}return{inserted:unique.length,skipped:rows.length-unique.length};}

/** Uploads only operational fields. The local national ID is deliberately absent. */
export function preparedCloudRow(sessionId:string,row:PreparedPerson,index:number){const groupCode=groupForSlot(row.slot);if(!groupCode)throw new Error(`「${row.name}」的排程時段無法對應組別：${row.slot}`);return{session_id:sessionId,sequence_no:row.sequence||index+1,employee_no:row.employeeNo,full_name:row.name,gender:row.gender,schedule_slot:row.slot,group_code:groupCode,planned_items:[row.item],note:row.extension?`院內分機：${row.extension}`:''};}
export async function uploadPreparedSchedule(sessionId:string,rows:PreparedPerson[]):Promise<ImportResult>{
  const existing=await listParticipants(sessionId);const existingEmployees=new Set(existing.map(person=>person.employeeNo));const seen=new Set<string>();const unique=rows.filter(row=>{if(existingEmployees.has(row.employeeNo)||seen.has(row.employeeNo))return false;seen.add(row.employeeNo);return true;});
  const payload=unique.map((row,index)=>preparedCloudRow(sessionId,row,index));
  if(payload.length){const{error}=await requireSupabase().from('participants').insert(payload);if(error)throw error;}
  return{inserted:payload.length,skipped:rows.length-payload.length};
}
