import {useMemo,useState} from 'react';
import {Bell,Users} from 'lucide-react';
import type {Participant,Session,WorkStatus} from '../../types';
import {callParticipant,updateWaitingStatus} from './service';

const waiting:Extract<WorkStatus,'等候中'|'上廁所'|'心電圖'|'先做其他'>[]=['等候中','上廁所','心電圖','先做其他'];
export function UltrasoundConsole({current,participants,onChanged,onError}:{current:Session|null;participants:Participant[];onChanged:()=>Promise<void>;onError:(message:string)=>void}){
  const[group,setGroup]=useState<'全部'|Participant['groupCode']>('全部');const[busy,setBusy]=useState('');
  const rows=useMemo(()=>participants.filter(p=>group==='全部'||p.groupCode===group),[participants,group]);
  const action=async(id:string,run:()=>Promise<void>)=>{setBusy(id);try{await run();await onChanged();}catch(e){onError(e instanceof Error?e.message:String(e));}finally{setBusy('');}};
  return <section><div className="mb-5"><h2 className="text-2xl font-black">超音波控制台</h2><p className="mt-1 text-slate-500">即時顯示目前場次的雲端今日名單、報到與候檢狀態。</p></div>
    {!current?<div className="rounded-2xl bg-white p-10 text-center text-slate-500">請先回健檢報到站選擇場次。</div>:<><div className="mb-4 flex flex-col justify-between gap-3 rounded-2xl bg-white p-5 shadow-sm sm:flex-row sm:items-center"><div><b>{current.companyName}｜{current.sessionDate}</b><p className="text-sm text-slate-500"><Users className="mr-1 inline" size={16}/>{participants.length} 人・已報到 {participants.filter(p=>p.checkedInAt).length} 人</p></div><div className="flex flex-wrap gap-2">{(['全部','A','B','C','D','E','F','G'] as const).map(code=><button key={code} className={group===code?'primary min-h-10 px-3':'secondary min-h-10 px-3'} onClick={()=>setGroup(code)}>{code}</button>)}</div></div>
      <div className="overflow-auto rounded-2xl bg-white shadow-sm"><table><thead><tr><th>組別</th><th>報到編號</th><th>姓名／工號</th><th>時段</th><th>項目</th><th>狀態</th><th>現場操作</th></tr></thead><tbody>{rows.map(p=><tr key={p.id} className={p.status==='已叫號'?'bg-amber-50':''}><td className="font-black">{p.groupCode}</td><td className="text-xl font-black text-teal-800">{p.checkinNo??'—'}</td><td><b>{p.name}</b><br/><span className="text-xs text-slate-500">{p.employeeNo}</span></td><td>{p.slot}</td><td>{p.plannedItems.join('、')||'—'}</td><td><span className="rounded-full bg-slate-100 px-3 py-1 text-sm font-bold">{p.status}</span></td><td><div className="flex items-center gap-2">{p.status==='等候中'&&<button disabled={!!busy} className="primary min-h-10 px-3" onClick={()=>void action(p.id,()=>callParticipant(p.id))}><Bell size={16}/>叫號</button>}{p.checkedInAt&&!['未報到','檢查中','已完成'].includes(p.status)&&<select disabled={!!busy} aria-label={`${p.name} 等候狀態`} className="input min-h-10 w-32 py-0" value={waiting.includes(p.status as typeof waiting[number])?p.status:'等候中'} onChange={e=>void action(p.id,()=>updateWaitingStatus(p.id,e.target.value as typeof waiting[number]))}>{waiting.map(s=><option key={s}>{s}</option>)}</select>}</div></td></tr>)}{!rows.length&&<tr><td colSpan={7} className="py-12 text-center text-slate-400">此分組尚無今日受檢者。</td></tr>}</tbody></table></div></>}
  </section>;
}
