import {useEffect,useMemo,useState} from 'react';
import {Bell,Plus,Users,X} from 'lucide-react';
import type {Examination,Participant,Session,UltrasoundItemName,WorkStatus} from '../../types';
import {ultrasoundItemNames} from '../../types';
import {formatAdditionalExaminationError,formatError} from '../../lib/errors';
import {callParticipant,updateWaitingStatus} from './service';
import {areValidUltrasoundItems,completedItems,enqueueAdditionalExamination,listExaminations,remainingPlannedItemsForParticipant} from '../examination/service';

const waiting:Extract<WorkStatus,'等候中'|'上廁所'|'心電圖'|'先做其他'>[]=['等候中','上廁所','心電圖','先做其他'];
export function UltrasoundConsole({current,participants,onChanged,onError}:{current:Session|null;participants:Participant[];onChanged:()=>Promise<void>;onError:(message:string)=>void}){
  const[group,setGroup]=useState<'全部'|Participant['groupCode']>('全部');const[busy,setBusy]=useState('');const[examinations,setExaminations]=useState<Examination[]>([]);const[adding,setAdding]=useState<Participant|null>(null);const[additionalItems,setAdditionalItems]=useState<UltrasoundItemName[]>([]);
  const reload=()=>listExaminations(participants.map(p=>p.id)).then(setExaminations);
  useEffect(()=>{void reload().catch(error=>onError(formatError(error)));},[participants]); // eslint-disable-line react-hooks/exhaustive-deps
  const examinationsByParticipant=useMemo(()=>{const result=new Map<string,Examination[]>();for(const examination of examinations)result.set(examination.participantId,[...(result.get(examination.participantId)??[]),examination]);return result;},[examinations]);
  const rows=useMemo(()=>participants.filter(p=>group==='全部'||p.groupCode===group),[participants,group]);
  const action=async(id:string,run:()=>Promise<void>,formatFailure:((error:unknown)=>string)=formatError)=>{setBusy(id);try{await run();await onChanged();await reload();}catch(e){onError(formatFailure(e));}finally{setBusy('');}};
  const openAdditional=(person:Participant)=>{const rounds=examinationsByParticipant.get(person.id)??[];setAdding(person);setAdditionalItems(remainingPlannedItemsForParticipant(person.plannedItems,rounds));};
  const toggle=(item:UltrasoundItemName)=>setAdditionalItems(old=>old.includes(item)?old.filter(value=>value!==item):[...old,item]);
  const submitAdditional=async()=>{if(!adding||!additionalItems.length)return;if(!areValidUltrasoundItems(additionalItems)){onError('追加檢查項目資料異常，請重新選擇。');return;}await action(adding.id,async()=>{await enqueueAdditionalExamination(adding.id,additionalItems);setAdding(null);},formatAdditionalExaminationError);};
  return <section><div className="mb-5"><h2 className="text-2xl font-black">超音波控制台</h2><p className="mt-1 text-slate-500">即時顯示目前場次的雲端今日名單、報到與候檢狀態。</p></div>
    {!current?<div className="rounded-2xl bg-white p-10 text-center text-slate-500">請先回健檢報到站選擇場次。</div>:<><div className="mb-4 flex flex-col justify-between gap-3 rounded-2xl bg-white p-5 shadow-sm sm:flex-row sm:items-center"><div><b>{current.companyName}｜{current.sessionDate}</b><p className="text-sm text-slate-500"><Users className="mr-1 inline" size={16}/>{participants.length} 人・已報到 {participants.filter(p=>p.checkedInAt).length} 人</p></div><div className="flex flex-wrap gap-2">{(['全部','A','B','C','D','E','F','G'] as const).map(code=><button key={code} className={group===code?'primary min-h-10 px-3':'secondary min-h-10 px-3'} onClick={()=>setGroup(code)}>{code}</button>)}</div></div>
      <div className="overflow-auto rounded-2xl bg-white shadow-sm"><table><thead><tr><th>組別</th><th>報到編號</th><th>姓名／工號</th><th>時段</th><th>方案／本輪項目</th><th>診間</th><th>狀態</th><th>完成件數</th><th>現場操作</th></tr></thead><tbody>{rows.map(p=>{const rounds=examinationsByParticipant.get(p.id)??[];const active=rounds.find(item=>item.status==='waiting'||item.status==='in_progress');const completed=rounds.filter(item=>item.status==='completed');return <tr key={p.id} className={p.status==='已叫號'?'bg-amber-50':''}><td className="font-black">{p.groupCode}</td><td className="text-xl font-black text-teal-800">{p.checkinNo??'—'}</td><td><b>{p.name}</b><br/><span className="text-xs text-slate-500">{p.employeeNo}</span></td><td>{p.slot}</td><td>{active?.roundNo&&active.roundNo>1?<><span className="mr-2 rounded-full bg-violet-100 px-2 py-1 text-xs font-black text-violet-800">追加</span>{active.selectedItems.join('、')}</>:p.plannedItems.join('、')||'—'}</td><td>{active?.roomId??completed.at(-1)?.roomId??'—'}</td><td><span className="rounded-full bg-slate-100 px-3 py-1 text-sm font-bold">{p.status}</span></td><td className="font-black">{completed.length?`${completed.reduce((sum,item)=>sum+item.itemCount,0)} 件`:'—'}</td><td><div className="flex items-center gap-2">{p.status==='等候中'&&<button disabled={!!busy} className="primary min-h-10 px-3" onClick={()=>void action(p.id,()=>callParticipant(p.id))}><Bell size={16}/>叫號</button>}{p.checkedInAt&&!['未報到','檢查中','已完成'].includes(p.status)&&<select disabled={!!busy} aria-label={`${p.name} 等候狀態`} className="input min-h-10 w-32 py-0" value={waiting.includes(p.status as typeof waiting[number])?p.status:'等候中'} onChange={e=>void action(p.id,()=>updateWaitingStatus(p.id,e.target.value as typeof waiting[number]))}>{waiting.map(s=><option key={s}>{s}</option>)}</select>}{p.status==='已完成'&&<button disabled={!!busy} className="secondary min-h-10 px-3" onClick={()=>openAdditional(p)}><Plus size={16}/>追加檢查</button>}</div></td></tr>})}{!rows.length&&<tr><td colSpan={9} className="py-12 text-center text-slate-400">此分組尚無今日受檢者。</td></tr>}</tbody></table></div></>}
    {adding&&<AdditionalDialog participant={adding} rounds={examinationsByParticipant.get(adding.id)??[]} selected={additionalItems} toggle={toggle} close={()=>setAdding(null)} submit={()=>void submitAdditional()} busy={Boolean(busy)}/>}</section>;
}
function AdditionalDialog({participant,rounds,selected,toggle,close,submit,busy}:{participant:Participant;rounds:Examination[];selected:UltrasoundItemName[];toggle:(item:UltrasoundItemName)=>void;close:()=>void;submit:()=>void;busy:boolean}){
  const done=completedItems(rounds);const remaining=remainingPlannedItemsForParticipant(participant.plannedItems,rounds);const other=ultrasoundItemNames.filter(item=>!remaining.includes(item));
  const choices=(items:readonly UltrasoundItemName[],markCompleted=false)=>items.length?<div className="space-y-2">{items.map(item=><label key={item} className="flex min-h-12 items-center gap-3 rounded-xl border p-3 font-bold"><input className="h-5 w-5" type="checkbox" checked={selected.includes(item)} onChange={()=>toggle(item)}/>{item}{markCompleted&&done.includes(item)?'（今日已完成）':''}</label>)}</div>:<p className="text-sm text-slate-500">無</p>;
  return <div className="fixed inset-0 z-50 grid bg-slate-950/60 p-3" role="dialog" aria-modal="true" aria-labelledby="additional-title"><div className="m-auto max-h-[95vh] w-full max-w-xl overflow-auto rounded-2xl bg-white p-6"><div className="flex justify-between gap-3"><div><h3 id="additional-title" className="text-xl font-black">追加檢查</h3><p className="mt-1 text-lg font-bold">{participant.name}｜{participant.checkinNo}</p></div><button className="secondary px-3" onClick={close}><X/></button></div><div className="my-4 grid gap-3 rounded-xl bg-slate-50 p-4 sm:grid-cols-3"><div><b>原排程</b><p>{participant.plannedItems.join('、')||'無'}</p></div><div><b>目前已完成</b><p>{done.map(item=>`✓ ${item}`).join('、')||'無'}</p></div><div><b>尚未完成</b><p>{remaining.map(item=>`○ ${item}`).join('、')||'無'}</p></div></div><h4 className="mb-2 font-black text-teal-800">原排程尚未完成</h4>{choices(remaining)}<h4 className="mb-2 mt-5 font-black text-violet-800">其他臨時追加項目</h4>{choices(other,true)}<div className="mt-6 flex justify-end gap-3"><button className="secondary" onClick={close}>取消</button><button disabled={busy||!selected.length} className="primary disabled:opacity-40" onClick={submit}>{busy?'加入中…':'加入等候'}</button></div></div></div>;
}
