-- Phase 1 schema. Apply with Supabase CLI; never expose the service-role key in the PWA.
create extension if not exists pgcrypto;
create type public.session_status as enum ('active','closing','closed');
create type public.work_status as enum ('未報到','等候中','已叫號','上廁所','心電圖','先做其他','檢查中','已完成');
create type public.examination_status as enum ('in_progress','completed');
create type public.station_role as enum ('admin','registration','console','clinic');
create table public.health_sessions(id uuid primary key default gen_random_uuid(),session_date date not null,company_name text not null check(length(trim(company_name))>0),status public.session_status not null default 'active',created_by uuid not null references auth.users,created_at timestamptz not null default now(),unique(session_date,company_name));
create table public.session_memberships(session_id uuid references public.health_sessions on delete cascade,user_id uuid references auth.users on delete cascade,role public.station_role not null,room_id text,primary key(session_id,user_id));
create table public.participants(id uuid primary key default gen_random_uuid(),session_id uuid not null references public.health_sessions on delete cascade,sequence_no integer not null check(sequence_no>0),national_id text not null check(length(trim(national_id))>0),employee_no text not null check(length(trim(employee_no))>0),full_name text not null,gender text not null default '',schedule_slot text not null,group_code text not null check(group_code in ('A','B','C','D','E','F','G')),planned_items text[] not null default '{}',checkin_sequence integer,checkin_no text,checked_in_at timestamptz,called_at timestamptz,note text not null default '',status public.work_status not null default '未報到',updated_at timestamptz not null default now(),unique(session_id,employee_no),unique(session_id,checkin_no),unique(session_id,group_code,checkin_sequence));
create index participants_session_national_idx on public.participants(session_id,national_id);
create table public.group_counters(session_id uuid references public.health_sessions on delete cascade,group_code text check(group_code in ('A','B','C','D','E','F','G')),last_value integer not null default 0,primary key(session_id,group_code));
create table public.ultrasound_items(id uuid primary key default gen_random_uuid(),name text not null unique,active boolean not null default true,sort_order integer not null default 0);
insert into public.ultrasound_items(name,sort_order) values ('腹部超音波',10),('甲狀腺超音波',20),('頸動脈超音波',30),('乳房超音波',40),('其他超音波',50);
create table public.examinations(id uuid primary key default gen_random_uuid(),participant_id uuid not null unique references public.participants on delete cascade,room_id text not null,started_at timestamptz not null,completed_at timestamptz,duration_seconds integer,actual_items text[] not null default '{}',item_count integer not null default 0,status public.examination_status not null default 'in_progress',updated_at timestamptz not null default now(),check((status='in_progress' and completed_at is null) or (status='completed' and completed_at is not null)));
create table public.registered_devices(id text primary key,display_name text not null,owner_id uuid not null references auth.users,revoked_at timestamptz,last_seen_at timestamptz not null default now());
create table public.clearance_requests(session_id uuid references public.health_sessions on delete cascade,device_id text references public.registered_devices,requested_at timestamptz not null default now(),acknowledged_at timestamptz,primary key(session_id,device_id));
create or replace function public.is_session_member(s uuid,roles public.station_role[] default null) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.session_memberships m where m.session_id=s and m.user_id=auth.uid() and (roles is null or m.role=any(roles))) $$;
create or replace function public.touch_updated_at() returns trigger language plpgsql set search_path='' as $$begin new.updated_at=now();return new;end$$;
create trigger participants_touch before update on public.participants for each row execute function public.touch_updated_at();create trigger examinations_touch before update on public.examinations for each row execute function public.touch_updated_at();
-- Transactional, idempotent allocation. Row lock prevents duplicate group numbers across devices.
create or replace function public.check_in_participant(p_participant_id uuid) returns public.participants language plpgsql security definer set search_path='' as $$declare p public.participants;c integer;begin select * into p from public.participants where id=p_participant_id for update;if not found then raise exception 'participant_not_found';end if;if not public.is_session_member(p.session_id,array['admin','registration']::public.station_role[]) then raise exception 'not_authorized';end if;if p.checkin_no is not null then return p;end if;insert into public.group_counters(session_id,group_code,last_value) values(p.session_id,p.group_code,1) on conflict(session_id,group_code) do update set last_value=public.group_counters.last_value+1 returning last_value into c;update public.participants set checkin_sequence=c,checkin_no=p.group_code||c,checked_in_at=now(),status='等候中' where id=p.id returning * into p;return p;end$$;
create or replace function public.set_waiting_status(p_participant_id uuid,p_status public.work_status) returns void language plpgsql security definer set search_path='' as $$declare s uuid;begin if p_status not in ('等候中','上廁所','心電圖','先做其他') then raise exception 'invalid_transition';end if;select session_id into s from public.participants where id=p_participant_id and status not in ('未報到','檢查中','已完成') for update;if not found or not public.is_session_member(s,array['admin','console']::public.station_role[]) then raise exception 'not_authorized_or_invalid_state';end if;update public.participants set status=p_status where id=p_participant_id;end$$;
create or replace function public.call_participant(p_participant_id uuid) returns void language plpgsql security definer set search_path='' as $$declare s uuid;begin select session_id into s from public.participants where id=p_participant_id and status='等候中' for update;if not found or not public.is_session_member(s,array['admin','console']::public.station_role[]) then raise exception 'not_authorized_or_invalid_state';end if;update public.participants set status='已叫號',called_at=now() where id=p_participant_id;end$$;
create or replace function public.start_examination(p_participant_id uuid,p_room_id text,p_started_at timestamptz default now()) returns public.examinations language plpgsql security definer set search_path='' as $$declare s uuid;e public.examinations;begin select session_id into s from public.participants where id=p_participant_id and status in ('等候中','已叫號') for update;if not found or not public.is_session_member(s,array['admin','clinic']::public.station_role[]) then raise exception 'not_authorized_or_not_checked_in';end if;insert into public.examinations(participant_id,room_id,started_at) values(p_participant_id,p_room_id,p_started_at) on conflict(participant_id) do update set room_id=excluded.room_id returning * into e;update public.participants set status='檢查中' where id=p_participant_id;return e;end$$;
-- Unique participant_id makes completion idempotent; a completed examination cannot increment twice.
create or replace function public.complete_examination(p_participant_id uuid,p_room_id text,p_started_at timestamptz,p_completed_at timestamptz,p_actual_items text[]) returns public.examinations language plpgsql security definer set search_path='' as $$declare s uuid;e public.examinations;begin select session_id into s from public.participants where id=p_participant_id for update;if not public.is_session_member(s,array['admin','clinic']::public.station_role[]) then raise exception 'not_authorized';end if;select * into e from public.examinations where participant_id=p_participant_id for update;if e.status='completed' then return e;end if;update public.examinations set room_id=p_room_id,started_at=p_started_at,completed_at=p_completed_at,duration_seconds=greatest(0,extract(epoch from(p_completed_at-p_started_at))::integer),actual_items=p_actual_items,item_count=cardinality(p_actual_items),status='completed' where participant_id=p_participant_id returning * into e;update public.participants set status='已完成' where id=p_participant_id;return e;end$$;
create or replace function public.acknowledge_device_clear(p_session_id uuid,p_device_id text) returns void language plpgsql security definer set search_path='' as $$begin if not public.is_session_member(p_session_id,null) then raise exception 'not_authorized';end if;update public.clearance_requests set acknowledged_at=now() where session_id=p_session_id and device_id=p_device_id;end$$;
create or replace function public.close_health_session(p_session_id uuid) returns jsonb language plpgsql security definer set search_path='' as $$declare pending integer;begin if not public.is_session_member(p_session_id,array['admin']::public.station_role[]) then raise exception 'not_authorized';end if;update public.health_sessions set status='closing' where id=p_session_id;select count(*) into pending from public.clearance_requests where session_id=p_session_id and acknowledged_at is null;if pending>0 then return jsonb_build_object('cloud_deleted',false,'pending_devices',pending);end if;delete from public.participants where session_id=p_session_id;update public.health_sessions set status='closed' where id=p_session_id;return jsonb_build_object('cloud_deleted',true,'pending_devices',0);end$$;
alter table public.health_sessions enable row level security;alter table public.session_memberships enable row level security;alter table public.participants enable row level security;alter table public.examinations enable row level security;alter table public.ultrasound_items enable row level security;alter table public.registered_devices enable row level security;alter table public.clearance_requests enable row level security;
create policy sessions_member_select on public.health_sessions for select using(public.is_session_member(id,null) or created_by=auth.uid());create policy sessions_admin_all on public.health_sessions for all using(public.is_session_member(id,array['admin']::public.station_role[]) or created_by=auth.uid()) with check(created_by=auth.uid());
create policy memberships_self_select on public.session_memberships for select using(user_id=auth.uid());create policy participants_member_select on public.participants for select using(public.is_session_member(session_id,null));create policy participants_registration_insert on public.participants for insert with check(public.is_session_member(session_id,array['admin','registration']::public.station_role[]));
create policy examinations_member_select on public.examinations for select using(exists(select 1 from public.participants p where p.id=participant_id and public.is_session_member(p.session_id,null)));create policy items_authenticated_select on public.ultrasound_items for select to authenticated using(true);create policy items_admin_write on public.ultrasound_items for all to authenticated using(exists(select 1 from public.session_memberships m where m.user_id=auth.uid() and m.role='admin'));
create policy devices_owner on public.registered_devices for all using(owner_id=auth.uid()) with check(owner_id=auth.uid());create policy clearance_member_select on public.clearance_requests for select using(public.is_session_member(session_id,null));
grant execute on function public.check_in_participant(uuid),public.set_waiting_status(uuid,public.work_status),public.call_participant(uuid),public.start_examination(uuid,text,timestamptz),public.complete_examination(uuid,text,timestamptz,timestamptz,text[]),public.acknowledge_device_clear(uuid,text),public.close_health_session(uuid) to authenticated;
alter publication supabase_realtime add table public.participants,public.examinations,public.clearance_requests;
